// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLOzIf9afoHG4eNvb5PDddHy87a0bQhbk',
    appId: '1:611312741043:web:7f6d06582c3e6c5df29ec6',
    messagingSenderId: '611312741043',
    projectId: 'grabbit-9e56e',
    authDomain: 'grabbit-9e56e.firebaseapp.com',
    storageBucket: 'grabbit-9e56e.firebasestorage.app',
    measurementId: 'G-W8F2Y9019B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6PEL5NjYkKRzCeO_pF9IbUKvMvOLiQkM',
    appId: '1:611312741043:android:d5714a931e44a968f29ec6',
    messagingSenderId: '611312741043',
    projectId: 'grabbit-9e56e',
    storageBucket: 'grabbit-9e56e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFXKJFWBd4rlbAdUYbcaRqsOvCOHt3-Jg',
    appId: '1:611312741043:ios:62171f863d288814f29ec6',
    messagingSenderId: '611312741043',
    projectId: 'grabbit-9e56e',
    storageBucket: 'grabbit-9e56e.firebasestorage.app',
    iosBundleId: 'com.example.classico',
  );
}
